#!/bin/sh -e

if test -z "$USER"; then
    echo USER is not set
    exit 1
fi

if test -z "$HOME"; then
    echo HOME is not set
    exit 1
fi

BASEDIR="$(pwd)"
if test "$BASEDIR" = "/"; then
    echo "Toolbox doesn't support '/' as current directory"
    exit 1
fi

TOOLBOX_SHELL=${TOOLBOX_SHELL:-/bin/bash}
IMAGE=${IMAGE:-agilestacks/toolbox}
IMAGE_VERSION=${IMAGE_VERSION:-stable}

if  test -z "${AWS_PROFILE}" && \
    test -x "$(which aws)" && \
    aws sts get-caller-identity > /dev/null 2>&1; then
    AWS_PROFILE=$(aws configure list | awk  '$1 ~ /^profile$/ {print $2}')
    export AWS_PROFILE
fi

envfile=$(mktemp)
env | grep -E '^(AWS_|GOOGLE_|AZURE_|TF_|TERM=|LANG=|LC_)' >"$envfile"
envadd=""
if test -s "$envfile"; then
    envadd="--env-file $envfile"
fi

docker_config=$HOME/.docker/config.json
if test -f $docker_config && grep osxkeychain $docker_config >/dev/null; then
    pruned_docker_config=$(mktemp /tmp/docker.json.XXXXXX)
    sed -e 's/osxkeychain//g' $docker_config > $pruned_docker_config
    maybe_docker_config="-v $pruned_docker_config:$HOME/.docker/config.json"
fi

# no pull if version is based on commit hashes
if test -n "$(echo $IMAGE_VERSION | sed -E -e 's/[0-9a-f]{7}-[0-9a-f]{7}//')"; then
    docker pull "$IMAGE:$IMAGE_VERSION" 2>/dev/null || true
fi
docker run -ti --rm \
    -h toolbox-"$(tty|sed -e 's|/dev/||')" \
    -e TMPDIR=/tmp \
    -e "USER=$USER" \
    -e "UID=$(id -u)" \
    -e "GID=$(id -g)" \
    -e "HOME=$HOME" \
    -e "SHELL=${TOOLBOX_SHELL}" \
    -e 'PS1=\u@\e[92m\h\e[0m \w $ ' \
    -v "$HOME:$HOME" \
    -v "$BASEDIR:$BASEDIR" \
    $maybe_docker_config \
    --privileged=true \
    --cap-add=NET_ADMIN \
    -w "$BASEDIR" \
    $envadd \
    "$IMAGE:$IMAGE_VERSION" "$@"
echo "Shutting down toolbox... bye!"

rm -f $envfile $pruned_docker_config
