name: 'Build and Push Toolbox for GCP'

on:
  workflow_dispatch:
    inputs:
      hubVersion:
        description: 'Hub CLI release version. Use "latest" or release number (ex. 1.0.0).'
        required: true
        default: 'latest'
      hubStateVersion:
        description: 'Hub State release version. Use "latest" or release number (ex. 1.0.0).'
        required: true
        default: 'latest'
      hubExtRef:
        description: 'Hub Extensions git ref.'
        required: true
        default: 'stable'
      hubExtCommit:
        description: 'Hub Extensions commit hash. If empty latest is used.'
        required: false
        default: ''
      customTag:
        description: 'Name of tag. Use "latest" to release image.'
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - id: 'info'
        name: 'Gather info'
        run: |
          HUB_CLI_VERSION="${{ github.event.inputs.hubVersion }}"
          if test "$HUB_CLI_VERSION" = "latest"; then
            HUB_CLI_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/agilestacks/hub/releases/latest" | jq -crM '.tag_name | select(.)' | cut -c 2-)
            if test -z "$HUB_CLI_VERSION"; then
              echo "Hub CLI version can't be empty"
              exit 1
            fi
          fi

          HUB_STATE_VERSION="${{ github.event.inputs.hubStateVersion }}"
          if test "$HUB_STATE_VERSION" = "latest"; then
            HUB_STATE_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/agilestacks/hub-state/releases/latest" | jq -crM '.tag_name | select(.)' | cut -c 2-)
            if test -z "$HUB_STATE_VERSION"; then
              echo "Hub State extension version can't be empty"
              exit 1
            fi
          fi

          HUB_CLI_VERSION_COMMIT=$(git ls-remote -q https://github.com/agilestacks/hub.git "v$HUB_CLI_VERSION" 2>/dev/null | cut -c-7)
          HUB_EXTENSIONS_VERSION=$(git ls-remote -q https://github.com/agilestacks/hub-extensions.git "${{ github.event.inputs.hubExtRef }}" 2>/dev/null | cut -c-7)
          HUB_STATE_VERSION_COMMIT=$(git ls-remote -q https://github.com/agilestacks/hub-state.git "v$HUB_STATE_VERSION" 2>/dev/null | cut -c-7)
          IMAGE_VERSION=$(echo "${{ github.sha }}" | cut -c-7)
          USER_FULLNAME=$(curl -s -H "Accept: application/vnd.github.v3+json" "${{ github.event.sender.url }}" | jq -crM '.name | select(.)')

          echo "::set-output name=toolboxVersion::$IMAGE_VERSION"
          echo "::set-output name=hubVersion::$HUB_CLI_VERSION"
          echo "::set-output name=hubVersionCommit::$HUB_CLI_VERSION_COMMIT"
          echo "::set-output name=hubExtVersion::$HUB_EXTENSIONS_VERSION"
          echo "::set-output name=hubStateVersion::$HUB_STATE_VERSION"
          echo "::set-output name=hubStateVersionCommit::$HUB_STATE_VERSION_COMMIT"
          echo "::set-output name=userFullname::$USER_FULLNAME"

      - id: 'versions'
        name: 'Calculate versions'
        run: |
          echo "::set-output name=hubExtVersion::${{ github.event.inputs.hubExtCommit || steps.info.outputs.hubExtVersion }}"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Login to GCR'
        uses: 'docker/login-action@v2'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v2'

      - name: Image meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            gcr.io/superhub/gcp-toolbox
          tags: |
            type=raw,value=${{ steps.info.outputs.toolboxVersion }}-${{ steps.info.outputs.hubVersionCommit }}-${{ steps.versions.outputs.hubExtVersion }}-${{ steps.info.outputs.hubStateVersionCommit }}
            type=raw,value=${{ github.event.inputs.customTag }},enable=${{ github.event.inputs.customTag != '' }}

      - name: 'Build and push'
        uses: "docker/build-push-action@v3"
        with:
          context: ./gcp-toolbox
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            USER_FULLNAME=${{ steps.info.outputs.userFullname || github.actor }}
            TOOLBOX_VERSION=${{ steps.info.outputs.toolboxVersion }}
            HUB_CLI_VERSION=${{ steps.info.outputs.hubVersion }}
            HUB_EXTENSIONS_VERSION=${{ steps.versions.outputs.hubExtVersion }}
            HUB_STATE_VERSION=${{ steps.info.outputs.hubStateVersion }}
