name: 'Build and Push - GCP Cloud Shell image'

on:
  workflow_dispatch:
    inputs:
      hubVersion:
        description: 'Hub CTL release version. Use "latest" or release number (ex. 1.0.0).'
        required: true
        default: 'latest'
      hubStateVersion:
        description: 'Hub State release version. Use "latest" or release number (ex. 1.0.0).'
        required: true
        default: 'latest'
      hubExtRef:
        description: 'Hub Extensions git ref.'
        required: true
        default: 'stable'
      hubExtCommit:
        description: 'Hub Extensions commit hash. If empty Hub Extensions git ref is used.'
        required: false
        default: ''
      customTag:
        description: 'Name of tag. Use "latest" to release image.'
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      -
        name: 'Checkout'
        uses: 'actions/checkout@v3'

      -
        id: 'info'
        name: 'Gather info'
        run: |
          HUB_CTL_VERSION="${{ github.event.inputs.hubVersion }}"
          if test "$HUB_CTL_VERSION" = "latest"; then
            HUB_CTL_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/epam/hubctl/releases/latest" | jq -crM '.tag_name | select(.)' | cut -c 2-)
            if test -z "$HUB_CTL_VERSION"; then
              echo "Hub CLI version can't be empty"
              exit 1
            fi
          fi

          HUB_STATE_VERSION="${{ github.event.inputs.hubStateVersion }}"
          if test "$HUB_STATE_VERSION" = "latest"; then
            HUB_STATE_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/epam/hub-state/releases/latest" | jq -crM '.tag_name | select(.)' | cut -c 2-)
            if test -z "$HUB_STATE_VERSION"; then
              echo "Hub State extension version can't be empty"
              exit 1
            fi
          fi

          HUB_CTL_VERSION_COMMIT=$(git ls-remote -q https://github.com/epam/hubctl.git "v$HUB_CTL_VERSION" 2>/dev/null | cut -c-7)
          HUB_EXTENSIONS_VERSION=$(git ls-remote -q https://github.com/epam/hub-extensions.git "${{ github.event.inputs.hubExtRef }}" 2>/dev/null | cut -c-7)
          HUB_STATE_VERSION_COMMIT=$(git ls-remote -q https://github.com/epam/hub-state.git "v$HUB_STATE_VERSION" 2>/dev/null | cut -c-7)
          IMAGE_VERSION=$(echo "${{ github.sha }}" | cut -c-7)

          echo "::set-output name=imageVersion::$IMAGE_VERSION"
          echo "::set-output name=hubVersion::$HUB_CTL_VERSION"
          echo "::set-output name=hubVersionCommit::$HUB_CTL_VERSION_COMMIT"
          echo "::set-output name=hubExtVersion::$HUB_EXTENSIONS_VERSION"
          echo "::set-output name=hubStateVersion::$HUB_STATE_VERSION"
          echo "::set-output name=hubStateVersionCommit::$HUB_STATE_VERSION_COMMIT"

      -
        id: 'versions'
        name: 'Calculate versions'
        run: |
          echo "::set-output name=hubExtVersion::${{ github.event.inputs.hubExtCommit || steps.info.outputs.hubExtVersion }}"

      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v2'
        with:
          platforms: linux/amd64

      -
        name: Image meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/epam/hub-toolbox-gcp-cloud-shell
          tags: |
            type=raw,value=${{ steps.info.outputs.imageVersion }}-${{ steps.info.outputs.hubVersionCommit }}-${{ steps.versions.outputs.hubExtVersion }}-${{ steps.info.outputs.hubStateVersionCommit }}
            type=raw,value=${{ github.event.inputs.customTag }},enable=${{ github.event.inputs.customTag != '' }}

      -
        name: 'Build and push'
        uses: "docker/build-push-action@v3"
        with:
          context: ./gcp-cloud-shell
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HUB_CTL_RELEASE_VERSION=${{ steps.info.outputs.hubVersion }}
            HUB_EXTENSIONS_VERSION=${{ steps.versions.outputs.hubExtVersion }}
            HUB_STATE_RELEASE_VERSION=${{ steps.info.outputs.hubStateVersion }}
